backend:
  name: git-gateway
  branch: master

media_folder: static/media
public_folder: /media

collections:
  - name: "contact"
    label: "Contact"
    slug: "{{slug}}"
    editor:
      preview: false
    files:
      - label: "Contact"
        name: "contact"
        file: "content/contact.md"
        fields:
          - { label: "Title", name: "title", widget: "hidden" }
          - { label: "Type", name: "type", widget: "hidden", default: "/contact" }
          - { label: "Parish Priest", name: "parishPriest", widget: "string" }
          - { label: "Address", name: "address", widget: "text" }
          - { label: "Telephone", name: "telephone", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Directions", name: "directions", widget: "markdown" }
          - { label: "Visiting Priests", name: "visitingPriests", widget: "markdown" }
  - name: "events"
    label: "Events"
    folder: "content/events"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Type", name: "type", widget: "hidden", default: "events" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Primary Image", name: "primaryImage", widget: "image", required: false }
      - { label: "Event Date", name: "eventDate", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "footer"
    label: "Footer"
    editor:
      preview: false
    files:
      - label: "Footer"
        name: "footer"
        file: "content/footer.md"
        fields:
          - { label: "Title", name: "title", widget: "hidden", default: "Footer" }
          - { label: "Type", name: "type", widget: "hidden", default: "/hidden" }
          - { label: "Copyright", name: "copyright", widget: "string" }
          - { label: "Oxford Charity Number", name: "oxfordCharityNumber", widget: "string" }
          - { label: "Middlesborough Charity Number", name: "middlesboroughCharityNumber", widget: "string" }
          - { label: "Credits", name: "credits", widget: "string" }
  - name: "groups"
    label: "Groups"
    editor:
      preview: false
    files:
      - label: Groups
        name: groups
        file: "content/groups.md"
        fields:
          - { label: "Title", name: "title", widget: "hidden", default: "Groups" }
          - { label: "Type", name: "type", widget: "hidden", default: "groups" }
          - label: "Groups"
            name: "groups"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "string"}
              - { label: "Url Slug", name: "urlSlug", widget: "string" }
              - { label: "Primary Image", name: "primaryImage", widget: "image", required: false, default: '' }
              - { label: "Group Type", name: "groupType", widget: "string", required: false, default: '' }
              - { label: "Body", name: "body", widget: "markdown" }
  - name: "home"
    label: "Home Page"
    editor:
      preview: false
    files:
      - label: "Home Page"
        name: "homepage"
        file: "content/homepage.md"
        fields:
          - { label: "Title", name: "title", widget: "hidden", default: "Home Page" }
          - { label: "Body", name: "body", widget: "markdown" }
  - name: "header"
    label: "Header"
    editor:
      preview: false
    files:
      - label: "Header"
        name: "header"
        file: "content/header.md"
        fields:
          - { label: "Title", name: "title", widget: "hidden", default: "Header" }
          - { label: "Type", name: "type", widget: "hidden", default: "/hidden" }
          - { label: "Header Image", name: "headerImage", widget: "image" }
  - name: "menu"
    label: "Menu"
    editor:
      preview: false
    files:
      - label: "Menu"
        name: "menu"
        file: "content/menu.md"
        fields:
          - { label: "Title", name: "title", widget: "hidden", default: "Menu" }
          - { label: "Type", name: "type", widget: "hidden", default: "/hidden" }
          - label: "Items"
            name: "items"
            widget: list
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }
              - { label: "Open in New Tab", name: "newTab", widget: "boolean", default: false, required: false }
  - name: "news"
    label: "News"
    folder: "content/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Type", name: "type", widget: "hidden", default: "news" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Primary Image", name: "primaryImage", widget: "image", required: false }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "policies"
    label: "Policies"
    folder: "content/policies"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Type", name: "type", widget: "hidden", default: "events" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Policy", name: "policy", widget: "file" }
  - name: "sacraments"
    label: "Sacraments"
    folder: "content/sacraments"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Type", name: "type", widget: "hidden", default: "events" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Primary Image", name: "primaryImage", widget: "image", required: false }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "sidebar"
    label: "Sidebar"
    editor:
      preview: false
    files:
      - label: "Sidebar"
        name: "sidebar"
        file: "content/sidebar.md"
        fields:
          - { label: "Title", name: "title", widget: "hidden", default: "Sidebar" }
          - { label: "Type", name: "type", widget: "hidden", default: "/hidden" }
          - label: "Groups"
            name: "groups"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string", required: false }
              - label: "Items"
                name: "items"
                widget: "list"
                fields:
                  - { label: "Url", name: "url", widget: "string" }
                  - { label: "Text", name: "text", widget: "string" }
                  - { label: "Show on New Tab", name: "newTab", widget: "boolean", default: false, required: false }
